default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--django]
      - id: flake8
